### ISSUE TITLE
Macros $__timeGroupAlias/$__timeGroup doesn't work 

### ISSUE THREAD

**Issue by iboobel** [doitintl/bigquery-grafana#187]
## Bug Report
Macros $__timeGroupAlias isn't replaced in SQL editor
According to the docs and blog article, $__timeGroupAlias should be replaced with some SQL.
I was making tests with this example 
```
SELECT
  $__timeGroupAlias(time_column,'5m'),
  value1
FROM
  metric_table
WHERE
  $__timeFilter(time_column)
```

## Expected Behavior
$__timeGroupAlias should be replaced with proper SQL

## Actual Behavior
Here is generated SQL 
```
SELECT $__timeGroupAlias(time_column,'5m'), value1 
FROM metric_table WHERE `time_column` BETWEEN TIMESTAMP_MILLIS (1576743785417) AND TIMESTAMP_MILLIS (1576765385418) LIMIT 840
```
and sql error `Syntax error: Illegal input character "$" at [2:3]`

## Steps to Reproduce the Problem

  1. Add a panel 
  2. Select data source Google Big query 
  3. Switch to plain SQL "Edit SQL" 

## Specifications

  - Version: 1.0.4
  - Platform: k8s (GKE+Container-Optimized OS from Google)  
  - Grafana Version: v6.3.6 Rancher edition

**Comment by avivl** [comment]
Are you trying to create the query manually or via the query builder?
Can you share the query?

**Comment by iboobel** [comment]
@avivl, I created query manually.
Here is query:

```
SELECT
  $__timeGroupAlias(time_column,'5m'),
  value1
FROM
  metric_table
WHERE
  $__timeFilter(time_column)
```

**Comment by avivl** [comment]
I can not guess what is time_column from the manual query therefore the macro will not work.
Your query is simple you should use the query builder

**Comment by iboobel** [comment]
I can't build a complicated query, because macros doesn't work.

Here is an example with the real table 
```
SELECT
  $__timeGroupAlias(timestamp,'5m'),
  jsonPayload.remoteip
FROM
  `xxxx.xxxx.stdout_*`
WHERE
  $__timeFilter(timestamp)
```
timestamp - is real column name

Here is query what I got:
`SELECT $__timeGroupAlias(timestamp,'5m'), jsonPayload.remoteip FROM xxx-xxx.xxx.stdout_* WHERE timestamp BETWEEN TIMESTAMP_MILLIS (1578117254822) AND TIMESTAMP_MILLIS (1578138854822) LIMIT 840`

$__timeGroupAlias wasn't replaced

**Comment by nielsbasjes** [comment]
Hi @avivl,
I ran into the same problem.
In my query I want to use the HLL_Count.Merge(`distinctVisitorsSketch`) in order to get the estimated count distinct into my graph. This is a function that is part of BigQuery and is not recognized by grafana.
The distinctVisitorsSketch column is of type BYTES and is created using HLL_COUNT.MERGE_PARTIAL as described here https://cloud.google.com/bigquery/docs/reference/standard-sql/hll_functions

Because these special functions are not supported in the grafana query builder I am forced to use the text based SQL editor. In there I really need the support of being able to tune the time period using the mentioned time macros.

**Comment by avivl** [comment]
@nielsbasjes I'll add support for HyperLogLog++ Functions #195
