### ISSUE TITLE
Alert is not working on grafana server running on x86_64 CentOS

### ISSUE THREAD

**Issue by linan-github** [doitintl/bigquery-grafana#252]
## Expected Behavior
Able to run alert from bigquery datasource

## Actual Behavior
grafana failed to load plugin doitintl-bigquery-datasource in  backend plugin, error in grafana log is as below
`grafana-server[22367]: t=2020-07-01T06:27:31+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=doitintl-bigquery-datasource error="fork/exec /var/lib/grafana/plugins/doitintl-bigquery-datasource/dist/doitintl-bigquery-datasource_linux_amd64: exec format error"`

grafana failed to evaluate alert, error in the log:
`grafana-server[11722]: t=2020-07-01T06:06:16+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=9 name="alert" error="tsdb.HandleRequest() error Could not find executor for data source type: doitintl-bigquery-datasource" changing state to=alerting`

## Steps to Reproduce the Problem

  1. grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/2.0.0.zip plugins install doitintl-bigquery-datasource
 

## Specifications

  - Version: v2.0.0 
  - Platform: CentOS Linux 3.10.0-1062.4.3.el7.x86_64
  - Grafana Version: v7.0.4

**Comment by LiorRacer** [comment]
Hi @linan-github,

Due to [Grafana docs](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/) and this [thread](https://community.grafana.com/t/how-to-create-a-signed-backend-plugin/30068/2)

There is no way yet to sign plugins, the solution for now is to allow unsigned plugin.
Add to Grafana.ini file under [plugin] the plugin id like so:

allow_loading_unsigned_plugins = "doitintl-bigquery-datasource"

![image](https://user-images.githubusercontent.com/13584904/88033508-2231e300-cb48-11ea-9668-e186ea22f8e8.png)
