### ISSUE TITLE
after installing 2.0.0 "plugin not found, no installed plugin with that id"

### ISSUE THREAD

**Issue by tomer-harpaz** [doitintl/bigquery-grafana#255]
## Bug Report
I've installed version 2.0.0
I'm running grafana in GKE and I've add the following command to my docker file
"RUN grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/2.0.0.zip plugins install doitintl-bigquery-datasource"
I can see it in the data source and when I try to add it I get an error
"plugin not found, no installed plugin with that id"

I also tried 
"RUN grafana-cli  plugins install doitintl-bigquery-datasource"
and I got a working bigquery but the earlier 1.08 version

## Expected Behavior
have a working bigquery plugin

## Actual Behavior
cannot add the the plugin, getting an error: 
"Plugin not found, no installed plugin with that id"

## Steps to Reproduce the Problem

  1.Added to the docker build "RUN grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/2.0.0.zip plugins install doitintl-bigquery-datasource"
  2. build push updated the deployment yaml
  3. try to add the datasource
  

## Specifications

  - Version:2.0.0
  - Platform: GKE
  - Grafana Version: Grafana v7.0.3

**Comment by tomashman8** [comment]
I am also seeing that same issue and in the logs it complains: 

t=2020-07-15T13:01:19+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"doitintl-bigquery-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/doit-bigquery-datasource/dist

**Comment by LiorRacer** [comment]
Hi all,

Due to [Grafana docs](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/) and this [thread](https://community.grafana.com/t/how-to-create-a-signed-backend-plugin/30068/2)

There is no way yet to sign plugins, the solution for now is to allow unsigned plugin.
Add to Grafana.ini file under `[plugin]` the plugin id like so:

allow_loading_unsigned_plugins = "doitintl-bigquery-datasource"

![image](https://user-images.githubusercontent.com/13584904/88032659-f2cea680-cb46-11ea-8af3-c5136a3a0254.png)

**Comment by tomashman8** [comment]
Thanks for your time, this fixed the problem for me.

**Comment by tomer-harpaz** [comment]
Thanks, worked for me as well.
