### ISSUE TITLE
BigQuery queries use time interval 1min rather than 1m for minute resolution

### ISSUE THREAD

**Issue by markschwarz** [doitintl/bigquery-grafana#306]
To reproduce: Create a panel with  $__timeGroup(hitTimestamp, 1m) for the grouping.

Expected: Queries with 1m $__interval draw at 1 minute intervals
Actual: Queries with 1m $interval are interpreted as 1 month (Source).  Queries with 1min are interpreted as 1 minute.  

Impact: This is prevents me from using $__interval very effectively, since it's common for the auto interval to be set to 1min.

Workaround: Force the min interval to 1h, so 1 minute is never encountered. This makes the data less useful, but way better than nothing!

**Comment by Sayrus** [comment]
Had the issue issue when using `timeGroup` with `$__interval`. I think it's because the function used to get the interval replaces `m` by `M`:
https://github.com/doitintl/bigquery-grafana/blob/0db71ef469d1198a75846264888f259f554b9588/src/datasource.ts#L39

The macro helpers says that `5m` is interpreted as 5 minutes so I think there is an issue there.
Quoting the value, as shown in the macro helpers, also breaks and lead to a zero value as interval.
