### ISSUE TITLE
Moving Average doesn't work

### ISSUE THREAD

**Issue by gomisha** [doitintl/bigquery-grafana#397]
## Bug Report

I have a panel that's pulling data correctly from BigQuery:

![image](https://user-images.githubusercontent.com/15269764/152164301-1304d90b-904e-4369-b2c6-f1c966695b75.png)

I want to create a moving average for this data and I do it like this:

![image](https://user-images.githubusercontent.com/15269764/152165060-d5812b9a-27da-4517-bc8e-247d80941e2c.png)

## Expected Behavior

A plot of the moving average of my data with the specified window size.

## Actual Behavior

After I add the Moving Average, I get this error:

![image](https://user-images.githubusercontent.com/15269764/152165217-c5b16810-c13c-4f88-a2f9-671ed2ec94d2.png)

When I go to the Query Inspector, it reports this error:

`"BigQuery: Syntax error: Expected ")" but got identifier `result2` at`

![image](https://user-images.githubusercontent.com/15269764/152165349-afe8eb15-9de8-48f1-b56f-c3caa49f8244.png)

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/15269764/152165060-d5812b9a-27da-4517-bc8e-247d80941e2c.png)

## Specifications

- Version: v2.0.2
- Platform: it's an enterprise Grafana installation and I can't see the platform that's used
- Grafana Version: v8.3.5

**Comment by Kay-Zee** [comment]
I ran into a similar problem while generating a similar dashboard.

The syntax error is appearing due to the tmp`results2`  alias, which is un-parsable, for that section, either the tmp needs to be brought into the back-ticks, or the back-ticks needs to be removed completely. I couldn't find a way to fix it just with the query interface, though maybe if there was an advance mode, we'd be able to get around it

<img width="1006" alt="Screen Shot 2022-02-06 at 1 19 57 PM" src="https://user-images.githubusercontent.com/2775157/152701850-0a01f8ce-70f5-48f4-92fb-a33d279e2e13.png">

**Comment by smnzhu** [comment]
@ofir5300 or someone, could you take a look?

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
