### ISSUE TITLE
Project id is not set on datasource on startup

### ISSUE THREAD

**Issue by jdelfino** [doitintl/bigquery-grafana#51]
## Bug Report
I have a grafana instance deployed in k8s with kube-prometheus. When loading a dashboard, bigquery queries are initially broken, until interacting with the query builder by editing a panel. The initial error shown is:

```
Invalid: Invalid project ID ''. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```

I've worked around this by setting `defaultProject` in `jsonData` for my datasource configuration (setting defaultProject is actually preferred for me, because it makes it easier to write dashboards reusable across my dev/prod projects), so this is not blocking me.

Not sure if this will be helpful or not, but I dug around in the code a bit to try to diagnose the problem - When no default project is set, It looks like project name starts as an empty string when the datasource is initialized: 

https://github.com/doitintl/bigquery-grafana/blob/2515b8e1d04f858d35590e6fa45f2c706ac0b913/src/datasource.ts#L71

Then, it is only set when either testing the datasource or changing the project in the query builder, neither of which happen automatically when loading a dashboard. If no default project is set in the json, could `getDefaultProject` be called at startup to prevent the error from being shown?

## Specifications

  - Version: 0.4.0
  - Platform: Linux
  - Grafana Version: 6.0.2

**Comment by spark2ignite** [comment]
@jdelfino let us know if this solves your issue.

**Comment by rchukh** [comment]
I had this issue each time Grafana server was restarted (manual restart) with v0.4.0.
Going to the Data sources and doing "Save & Test" fixes the issue until the next restart.

After updating to the latest master (in order to test the fix for this is linked commit) this error is present both on the dashboard and on Data Source config page after clicking "Save & Test" (so the workaround is not working anymore).

Some additional info:

- The plugin is set to use the "GCE Default Service Account" (with BigQuery API).
- I can see from the browser network calls that the project is successfully listed in the response of the "/projects" call (<grafana_url>/api/datasources/proxy/1/bigquery/v2/projects), but the next call to the "/datasets" is broken (missing the project in the URL) and looks like this - <grafana_url>/api/datasources/proxy/1/bigquery/v2/projects//datasets
- The browser - Firefox 66.0.3

**Comment by avivl** [comment]
@rchukh just to be on the safe side did you make sure that you have a service account that is setup as the default account for the virtual machine/node and that the service account has been given read access to the BigQuery API.

**Comment by rchukh** [comment]
@avivl Checked again (just in case) - the VM service account is a default compute engine service account with the role "Editor" and explicitly enabled BigQuery access within "Cloud API access scopes" of that specific VM.

**Comment by avivl** [comment]
@rchukh can you check with the latest version from master?

**Comment by rchukh** [comment]
@avivl 
Just did (updated Grafana to the latest 6.1.6 before checking).

It now fails silently - UI shows "Successfully queried the BigQuery API.", but the network tab (Cache is disabled) is full of errors.

---

There are 4 calls to "**/api/datasources/proxy/1/bigquery/v2/projects**" and all of them are just getting Status "(canceled)" without the actual response.

There are 4 calls to datasets that seem to be incorrect now, and omit the project id - "/api/datasources/proxy/1/bigquery/v2/projects/undefined/datasets" - note the *undefined* in the URL.
3 of those calls - fail with the same status "(canceled)". 4 call is "200 OK" (while still using the "undefined" part of the URL), and the only response is some generic JSON:

```
{
  "kind": "bigquery#datasetList",
  "etag": "1B2M2Y8AsgTpgAmY7PhCfg=="
}
```

**Comment by rchukh** [comment]
Tested again with the provided service account through JSON file.
Works fine on 0.4.0 (even after Grafana reboot).
On latest master - behaves the same way as described above.
