### ISSUE TITLE
Grouping time with $__interval fails

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#97]
## Bug Report

When I use `$__timeGroupAlias(measured_at,$__interval),` a query is executed but data points fall outside the time range.

When comparing the type of queries that are generated 

```
$__timeGroupAlias(measured_at,1h)
```

translates into

```sql
TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(measured_at), 3600) * 3600)
```

which works fine and returns a nice graph. However

```
$__timeGroupAlias(measured_at,$__interval)
```

turns into

```
TIMESTAMP(  (PARSE_DATE( "%Y-%m-%d",CONCAT( CAST((EXTRACT(YEAR FROM measured_at)) AS STRING),'-',CAST((EXTRACT(MONTH FROM measured_at)) AS STRING),'-','01'))))
```

I would imagine the second query to look the same as the first but with a different number of seconds.

## Expected Behavior

`$__timeGroupAlias(measured_at,$__interval)` to group in such a way that the same query can be used to graph either the last 24 hours or the last 5 years.

## Actual Behavior

Data points outside time range.

## Specifications

  - Version: `0.6.1`
  - Platform: docker image `grafana/grafana`
  - Grafana Version: `6.2.4`

**Comment by JorritSalverda** [comment]
@avivl in version `1.0.0` which should have the fix for this issue

```
$__timeGroupAlias(measured_at,$__interval)
```

still turns into 

```
TIMESTAMP(  (PARSE_DATE( "%Y-%m-%d",CONCAT( CAST((EXTRACT(YEAR FROM `measured_at`)) AS STRING),'-',CAST((EXTRACT(MONTH FROM `measured_at`)) AS STRING),'-','01')))),
```

resulting in the same data points outside time range issue. 

It seems that regardless of the changes it still enters this if statement:

https://github.com/doitintl/bigquery-grafana/blob/6eb36a02d19a3e75b3869a74005adb0e35302caa/src/bigquery_query.ts#L114-L128

**Comment by JorritSalverda** [comment]
And when using 

```
$__timeGroupAlias(measured_at,10m)
```

- which should now be supported, where previously only the values from the case statement were allowed - it turns into

```
TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`measured_at`), 26297430) * 26297430),
```

instead of the expected

```
TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(measured_at), 600) * 600)
```

**Comment by avivl** [comment]
@JorritSalverda `m` is month `min` is for minutes so the calculation is correct

**Comment by JorritSalverda** [comment]
Ah yes, I keep forgetting that. With `min` the second notation works as expected indeed.

**Comment by DennisTT** [comment]
I think I'm still seeing this issue, using the latest master zip on Grafana 6.2.5.  If I use "GROUP BY time($__interval, none)" on a graph with timespan of an hour, the query I see in the Query Inspector shows the daily grouping "TIMESTAMP( (PARSE_DATE( "%Y-%m-%d",CONCAT( CAST((EXTRACT(YEAR FROM `date`)) AS STRING),'-',CAST((EXTRACT(MONTH FROM `date`)) AS STRING),'-','01'))))" instead of the grouping by hours/minutes/seconds.

Anyone else?

**Comment by avivl** [comment]
@DennisTT can you share the query that you are writing and the output from the dev console?

**Comment by DennisTT** [comment]
@avivl 

`
#standardSQL
SELECT
 $__timeGroupAlias(date,$__interval,1min),
  count(`id`) AS Complete
FROM `exampletablepath`
WHERE
  $__timeFilter(date) AND
  active = 0
GROUP BY 1
ORDER BY 1
`

This is the generated SQL from the Query Inspector with a dashboard timespan of last 3 hours:
`
#standardSQL\nSELECT\n TIMESTAMP(  (PARSE_DATE( \"%Y-%m-%d\",CONCAT( CAST((EXTRACT(YEAR FROM `date`)) AS STRING),'-',CAST((EXTRACT(MONTH FROM `date`)) AS STRING),'-','01')))),\n  count(`id`) AS Complete\nFROM `exampletablepath`\nWHERE\n  `date` BETWEEN TIMESTAMP_MILLIS (1564503818182) AND TIMESTAMP_MILLIS (1564514618182) AND\n  active = 0\nGROUP BY 1\nORDER BY 1 LIMIT 1000000
`
Sorry I'm not too familiar with Grafana, is there another dev console you'd like info from?

I tried to do [some debugging](https://github.com/DennisTT/bigquery-grafana/commits/master), and it seems like the [query options](https://github.com/DennisTT/bigquery-grafana/commit/d8e554fc49131cf5cad54fde49b9110e39c3f70c) passes interval as "1m" (intervalMs = 60000) up to 2 years dashboard, then "2m" (intervalMs=120000) up to 6 years dashboard.  So actually the resolution of interval (assuming "m" == Month) works fine for graphs which are like 1+ years time span.  However, it doesn't work when the dashboard timespan is set to anything shorter.

I'm quite new to Grafana and this plugin, so if I've overlooked something, please let me know!

There's also seems to be a discrepancy between interval and intervalMs, because it seems like whatever is calculating intervalMs is assuming "m" is a minute, whereas "interval" thinks "m" is month.

**Comment by avivl** [comment]
@DennisTT is your time filed name is date?
Try to quite it \`date\`

**Comment by DennisTT** [comment]
@avivl You mean like this?
```
#standardSQL
SELECT
 $__timeGroupAlias(`date`,$__interval,1min),
  count(`id`) AS Complete
FROM `exampletablename`
WHERE
  $__timeFilter(`date`) AND
  active = 0
GROUP BY 1
ORDER BY 1
```
In this case I get a syntax error and the Query Inspector shows the special functions don't parse at all:
```
Object
xhrStatus:"complete"
request:Object
method:"POST"
data:Object
query:"#standardSQL SELECT $__timeGroupAlias(`date`,1m,1min), count(`id`) AS Complete FROM `exampletablename` WHERE $__timeFilter(`date`) AND active = 0 GROUP BY 1 ORDER BY 1 LIMIT 1000000"
useLegacySql:false
useQueryCache:true
url:"api/datasources/proxy/6/bigquery/v2/projects/xxx/queries"
response:Object
error:Object
code:400
message:"Syntax error: Illegal input character "$" at [3:2]"
errors:Array[1]
0:Object
message:"Syntax error: Illegal input character "$" at [3:2]"
domain:"global"
reason:"invalidQuery"
location:"q"
locationType:"parameter"
status:"INVALID_ARGUMENT"
```

**Comment by avivl** [comment]
@DennisTT you are missing the project and dataset name in your WHERE clouse. 
`FROM  my-project.my-dataset.exampletablename`

Also try to remove $__interval from __timeGroupAlias

**Comment by avivl** [comment]
The $__interval is only used if you set it from the query builder UI

**Comment by DennisTT** [comment]
Hi @avivl,

> @DennisTT you are missing the project and dataset name in your WHERE clouse.
> `FROM my-project.my-dataset.exampletablename`
Sorry, yes I do have the project and data set in the actual query, I just redacted the whole thing to 'exampletablename' for privacy.

> 
> Also try to remove $__interval from __timeGroupAlias

>
> The $__interval is only used if you set it from the query builder UI

What would I replace it with?  Correct me if I'm wrong, the $__interval is supposed to be automatically calculating the appropriate resolution to group values to display on the dashboard, depending on the dashboard's timespan.  I want to avoid a hardcoded value like "1 min" which would be too fine of a resolution for a dashboard timespan of say 1 year.

**Comment by avivl** [comment]
#standardSQL
SELECT
 $__timeGroupAlias(`date`,1min),
  count(`id`) AS Complete
FROM my-project.my-dataset.exampletablenam
WHERE
  $__timeFilter(`date`) AND
  active = 0
GROUP BY 1
ORDER BY 1

**Comment by artjomzab** [comment]
@avivl when max datapoint is set to auto and I filter the dashboard for say more than 12 hours, not all data is shown. The query limit is set automatically, but it does not depend on the selected timeframe. It results in graphs like this:

![Screenshot 2019-09-16 10 03 27](https://user-images.githubusercontent.com/524580/64942402-3c849b80-d869-11e9-92f2-2fcdb5dfc150.png)

So I tried to group the data using query builder UI: GROUP BY time($__interval, 1min) which results in a query like this:

```
#standardSQL
SELECT
 TIMESTAMP(  (PARSE_DATE( "%Y-%m-%d",CONCAT( CAST((EXTRACT(YEAR FROM `timestamp`)) AS STRING),'-',CAST((EXTRACT(MONTH FROM `timestamp`)) AS STRING),'-','01')))),
  CAST (`attribute`AS String ) AS metric,
  avg(`value`) AS value
FROM `project-id.dataset.table`
WHERE
  `timestamp` BETWEEN TIMESTAMP_MILLIS (1568611143961) AND TIMESTAMP_MILLIS (1568621943961) AND
  attribute = 'someAttr'
GROUP BY 1,2
ORDER BY 1,2 LIMIT 658
```

However this query returns just one datapoint and the graph displays: data points out of range. How is the value for $__interval determined? I would expect it be determined based on the selected timeframe. E.g. when timeframe spans minutes, $__interval is 1min, when the timeframe spans hours, $__interval is 1h, etc.

**Comment by avivl** [comment]
If you don't set max data point manuly the query limit is set from what the Grafan is getting from the browser

**Comment by artjomzab** [comment]
@avivl so the solution simply is to have a very high max data point value, like 100.000?

**Comment by avivl** [comment]
correct

**Comment by ptomasroos** [comment]
> The $__interval is only used if you set it from the query builder UI

@avivl 

Is there any way we can use the $__interval replacement with manual SQL as well? Makes sense to get dynamic resolutions depending on interval even though running a manual sql query

**Comment by avivl** [comment]
@ptomasroos currently it's not on the roadmap but I'll take a look

**Comment by ptomasroos** [comment]
Thanks for the quick reply @avivl and for looking into it!

Saw that the MySQL datasource has this!
